
- SKU: 2APLOW21CYN001
  category: Ladies
  collection: Test Collection
  brand:  LEVADE
  name: Leap Horse Hoodie (Adult)
  price: '1000'
  description: To celebrate the start of the 2021/22 racing season, LEVADE has teamed up with up-and-coming knitwear label Cynthia & Xiao - founded by Cynthia Mak and Xiao Xiao - to launch exclusive equestrian-themed adults' and kids' apparel that resonates with the Club's rich heritage.
  tags:
    []
- SKU: 1APLTS20HKK003
  category:
    - Ladies
    - Clothing
    - Tops
  collection: Personalise Collection
  brand:  LEVADE
  name: Women's Interlock Polo
  price: '500'
  discount-price: '800'
  description: This is a test description
  tags:
    - Pre-order
    - Exclusive
- SKU: 2APLOW21CYN001
  category: Ladies
  collection: Test Collection
  brand:  LEVADE
  name: Leap Horse Hoodie (Adult)
  price: '1000'
  description: To celebrate the start of the 2021/22 racing season, LEVADE has teamed up with up-and-coming knitwear label Cynthia & Xiao - founded by Cynthia Mak and Xiao Xiao - to launch exclusive equestrian-themed adults' and kids' apparel that resonates with the Club's rich heritage.
  tags:
    []
- SKU: 2APLOW21CYN001
  category: Ladies
  collection: Test Collection
  brand:  LEVADE
  name: Leap Horse Hoodie (Adult)
  price: '1000'
  description: To celebrate the start of the 2021/22 racing season, LEVADE has teamed up with up-and-coming knitwear label Cynthia & Xiao - founded by Cynthia Mak and Xiao Xiao - to launch exclusive equestrian-themed adults' and kids' apparel that resonates with the Club's rich heritage.
  tags:
    []
- SKU: 2APLOW21CYN001
  category: Ladies
  collection: Test Collection
  brand:  LEVADE
  name: Leap Horse Hoodie (Adult)
  price: '1000'
  description: To celebrate the start of the 2021/22 racing season, LEVADE has teamed up with up-and-coming knitwear label Cynthia & Xiao - founded by Cynthia Mak and Xiao Xiao - to launch exclusive equestrian-themed adults' and kids' apparel that resonates with the Club's rich heritage.
  tags:
    []
- SKU: 2APLOW21CYN001
  category: Ladies
  collection: Test Collection
  brand:  LEVADE
  name: Leap Horse Hoodie (Adult)
  price: '1000'
  description: To celebrate the start of the 2021/22 racing season, LEVADE has teamed up with up-and-coming knitwear label Cynthia & Xiao - founded by Cynthia Mak and Xiao Xiao - to launch exclusive equestrian-themed adults' and kids' apparel that resonates with the Club's rich heritage.
  tags:
    []